apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeintel
  namespace: kubeintel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeintel
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "pods/log", "namespaces", "events", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeintel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeintel
subjects:
  - kind: ServiceAccount
    name: kubeintel
    namespace: kubeintel
